//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sun Dec 23 15:43:19 2012 by ROOT version 5.32/00)
//      from the StreamerInfo in file /storage/epp2/phseaj/exercise/prod5_analysis.root
//////////////////////////////////////////////////////////


#ifndef ND__TAnalysisHeaderModuleBase_h
#define ND__TAnalysisHeaderModuleBase_h
namespace ND {
class TAnalysisHeaderModuleBase;
} // end of namespace.

#include "ND__TAnalysisModuleBase.h"

namespace ND {
class TAnalysisHeaderModuleBase : public ND::TAnalysisModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TAnalysisHeaderModuleBase();
   TAnalysisHeaderModuleBase(const TAnalysisHeaderModuleBase & );
   virtual ~TAnalysisHeaderModuleBase();

   ClassDef(TAnalysisHeaderModuleBase,2); // Generated by MakeProject.
};
} // namespace
#endif
