//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Sun Dec 23 15:43:19 2012 by ROOT version 5.32/00)
//      from the StreamerInfo in file /storage/epp2/phseaj/exercise/prod5_analysis.root
//////////////////////////////////////////////////////////


#ifndef ND__TBasicDataQualityModule_h
#define ND__TBasicDataQualityModule_h
namespace ND {
class TBasicDataQualityModule;
} // end of namespace.

#include "ND__TAnalysisHeaderModuleBase.h"

namespace ND {
class TBasicDataQualityModule : public ND::TAnalysisHeaderModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TBasicDataQualityModule();
   TBasicDataQualityModule(const TBasicDataQualityModule & );
   virtual ~TBasicDataQualityModule();

   ClassDef(TBasicDataQualityModule,2); // Generated by MakeProject.
};
} // namespace
#endif
