//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Dec  5 18:09:50 2012 by ROOT version 5.30/02)
//      from the StreamerInfo in file /storage/physics/phujbk/4_reconstructed_path_analysis/part1/prod5_analysis.root
//////////////////////////////////////////////////////////


#ifndef ND__GRooTrackerVtx_h
#define ND__GRooTrackerVtx_h
namespace ND {
class GRooTrackerVtx;
} // end of namespace.

#include "ND__JNuBeamFlux.h"
#include "TObjString.h"

namespace ND {
class GRooTrackerVtx : public ND::JNuBeamFlux {

public:
// Nested classes declaration.

public:
// Data Members.
   TObjString* EvtCode;     //generator-specific string with 'event code'
   int         EvtNum;      //event num.
   double      EvtXSec;     //cross section for selected event (1E-38 cm2)
   double      EvtDXSec;    //cross section for selected event kinematics (1E-38 cm2 /{K^n})
   double      EvtWght;     //weight for that event
   double      EvtProb;     //probability for that event (given cross section, path lengths, etc)
   double      EvtVtx[4];    //event vertex position in detector coord syst (SI)
   int         StdHepN;      //number of particles in particle array 
   int         StdHepPdg[100];    //pdg codes (& generator specific codes for pseudoparticles)
   int         StdHepRescat[100];    //generator-specific status code
   int         StdHepStatus[100];    //generator-specific status code
   double      StdHepX4[100][4];     //4-x (x, y, z, t) of particle in hit nucleus frame (fm)
   double      StdHepP4[100][4];     //4-p (px,py,pz,E) of particle in LAB frame (GeV)
   double      StdHepPolz[100][3];    //polarization vector
   int         StdHepFd[100];         //first daughter
   int         StdHepLd[100];         //last  daughter 
   int         StdHepFm[100];         //first mother
   int         StdHepLm[100];         //last  mother
   int         G2NeutEvtCode;         //NEUT-like reaction code for the GENIE event   
   TObjString* GeomPath;              //
   TObjString* GeneratorName;         //
   TObjString* OrigFileName;          //
   TObjString* OrigTreeName;          //
   int         OrigEvtNum;            //
   int         OrigTreeEntries;       //
   double      OrigTreePOT;           //
   double      TimeInSpill;           //
   int         TruthVertexID;         //

   GRooTrackerVtx();
   GRooTrackerVtx(const GRooTrackerVtx & );
   virtual ~GRooTrackerVtx();

   ClassDef(GRooTrackerVtx,3); // Generated by MakeProject.
};
} // namespace
#endif
