//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Dec  5 18:09:50 2012 by ROOT version 5.30/02)
//      from the StreamerInfo in file /storage/physics/phujbk/4_reconstructed_path_analysis/part1/prod5_analysis.root
//////////////////////////////////////////////////////////


#ifndef ND__TTrackerECALPi0ReconModule_h
#define ND__TTrackerECALPi0ReconModule_h
namespace ND {
class TTrackerECALPi0ReconModule;
} // end of namespace.

#include "ND__TAnalysisReconModuleBase.h"

namespace ND {
class TTrackerECALPi0ReconModule : public ND::TAnalysisReconModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TTrackerECALPi0ReconModule();
   TTrackerECALPi0ReconModule(const TTrackerECALPi0ReconModule & );
   virtual ~TTrackerECALPi0ReconModule();

   ClassDef(TTrackerECALPi0ReconModule,2); // Generated by MakeProject.
};
} // namespace
#endif
