//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Dec  5 18:09:50 2012 by ROOT version 5.30/02)
//      from the StreamerInfo in file /storage/physics/phujbk/4_reconstructed_path_analysis/part1/prod5_analysis.root
//////////////////////////////////////////////////////////


#ifndef ND__TAnalysisHeaderModuleBase_h
#define ND__TAnalysisHeaderModuleBase_h
namespace ND {
class TAnalysisHeaderModuleBase;
} // end of namespace.

#include "ND__TAnalysisModuleBase.h"

namespace ND {
class TAnalysisHeaderModuleBase : public ND::TAnalysisModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TAnalysisHeaderModuleBase();
   TAnalysisHeaderModuleBase(const TAnalysisHeaderModuleBase & );
   virtual ~TAnalysisHeaderModuleBase();

   ClassDef(TAnalysisHeaderModuleBase,2); // Generated by MakeProject.
};
} // namespace
#endif
