//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Dec  5 18:09:50 2012 by ROOT version 5.30/02)
//      from the StreamerInfo in file /storage/physics/phujbk/4_reconstructed_path_analysis/part1/prod5_analysis.root
//////////////////////////////////////////////////////////


#ifndef ND__TAnalysisTruthModuleBase_h
#define ND__TAnalysisTruthModuleBase_h
namespace ND {
class TAnalysisTruthModuleBase;
} // end of namespace.

#include "ND__TAnalysisModuleBase.h"

namespace ND {
class TAnalysisTruthModuleBase : public ND::TAnalysisModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TAnalysisTruthModuleBase();
   TAnalysisTruthModuleBase(const TAnalysisTruthModuleBase & );
   virtual ~TAnalysisTruthModuleBase();

   ClassDef(TAnalysisTruthModuleBase,2); // Generated by MakeProject.
};
} // namespace
#endif
