//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Dec  5 18:09:50 2012 by ROOT version 5.30/02)
//      from the StreamerInfo in file /storage/physics/phujbk/4_reconstructed_path_analysis/part1/prod5_analysis.root
//////////////////////////////////////////////////////////


#ifndef ND__TNRooTrackerVtxModule_h
#define ND__TNRooTrackerVtxModule_h
namespace ND {
class TNRooTrackerVtxModule;
} // end of namespace.

#include "ND__TRooTrackerVtxModuleBase.h"

namespace ND {
class TNRooTrackerVtxModule : public ND::TRooTrackerVtxModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TNRooTrackerVtxModule();
   TNRooTrackerVtxModule(const TNRooTrackerVtxModule & );
   virtual ~TNRooTrackerVtxModule();

   ClassDef(TNRooTrackerVtxModule,2); // Generated by MakeProject.
};
} // namespace
#endif
