//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Dec  5 18:09:50 2012 by ROOT version 5.30/02)
//      from the StreamerInfo in file /storage/physics/phujbk/4_reconstructed_path_analysis/part1/prod5_analysis.root
//////////////////////////////////////////////////////////


#ifndef ND__ToaAnalysisUtils_h
#define ND__ToaAnalysisUtils_h
namespace ND {
class ToaAnalysisUtils;
} // end of namespace.

#include "TObject.h"

namespace ND {
class ToaAnalysisUtils : public TObject {

public:
// Nested classes forward declaration.
enum EParticleCategory { kDefault_EParticleCategory };
enum ESubdetector { kDefault_ESubdetector };

public:
// Nested classes declaration.

public:
// Data Members.

   ToaAnalysisUtils();
   ToaAnalysisUtils(const ToaAnalysisUtils & );
   virtual ~ToaAnalysisUtils();

   ClassDef(ToaAnalysisUtils,2); // Generated by MakeProject.
};
} // namespace
#endif
