//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Dec  5 18:09:50 2012 by ROOT version 5.30/02)
//      from the StreamerInfo in file /storage/physics/phujbk/4_reconstructed_path_analysis/part1/prod5_analysis.root
//////////////////////////////////////////////////////////


#ifndef ND__TExample2010aAnalysis1Module_h
#define ND__TExample2010aAnalysis1Module_h
namespace ND {
class TExample2010aAnalysis1Module;
} // end of namespace.

#include "ND__TAnalysisReconModuleBase.h"

namespace ND {
class TExample2010aAnalysis1Module : public ND::TAnalysisReconModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.
   Double_t    fTimeOffset;    //

   TExample2010aAnalysis1Module();
   TExample2010aAnalysis1Module(const TExample2010aAnalysis1Module & );
   virtual ~TExample2010aAnalysis1Module();

   ClassDef(TExample2010aAnalysis1Module,2); // Generated by MakeProject.
};
} // namespace
#endif
