//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Dec  5 18:09:50 2012 by ROOT version 5.30/02)
//      from the StreamerInfo in file /storage/physics/phujbk/4_reconstructed_path_analysis/part1/prod5_analysis.root
//////////////////////////////////////////////////////////


#ifndef ND__TAnalysisReconModuleBase_h
#define ND__TAnalysisReconModuleBase_h
namespace ND {
class TAnalysisReconModuleBase;
} // end of namespace.

#include "ND__TAnalysisModuleBase.h"

namespace ND {
class TAnalysisReconModuleBase : public ND::TAnalysisModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TAnalysisReconModuleBase();
   TAnalysisReconModuleBase(const TAnalysisReconModuleBase & );
   virtual ~TAnalysisReconModuleBase();

   ClassDef(TAnalysisReconModuleBase,2); // Generated by MakeProject.
};
} // namespace
#endif
