//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Dec  5 18:09:50 2012 by ROOT version 5.30/02)
//      from the StreamerInfo in file /storage/physics/phujbk/4_reconstructed_path_analysis/part1/prod5_analysis.root
//////////////////////////////////////////////////////////


#ifndef ND__TRooTrackerVtxModuleBase_h
#define ND__TRooTrackerVtxModuleBase_h
namespace ND {
class TRooTrackerVtxModuleBase;
} // end of namespace.

#include "ND__TAnalysisTruthModuleBase.h"

namespace ND {
class TRooTrackerVtxModuleBase : public ND::TAnalysisTruthModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.
   bool        fPassThroughPresent;    //

   TRooTrackerVtxModuleBase();
   TRooTrackerVtxModuleBase(const TRooTrackerVtxModuleBase & );
   virtual ~TRooTrackerVtxModuleBase();

   ClassDef(TRooTrackerVtxModuleBase,2); // Generated by MakeProject.
};
} // namespace
#endif
