//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Nov 21 16:59:09 2012 by ROOT version 5.32/00)
//      from the StreamerInfo in file /storage/epp2/phseaj/exercise/prod5_analysis.root
//////////////////////////////////////////////////////////


#ifndef ND__TData_h
#define ND__TData_h
namespace ND {
class TData;
} // end of namespace.

#include "ND__TDatum.h"

namespace ND {
class TData : public ND::TDatum {

public:
// Nested classes declaration.

public:
// Data Members.

   TData();
   TData(const TData & );
   virtual ~TData();

   ClassDef(TData,4); // Generated by MakeProject.
};
} // namespace
#endif
