//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Nov 21 16:59:09 2012 by ROOT version 5.32/00)
//      from the StreamerInfo in file /storage/epp2/phseaj/exercise/prod5_analysis.root
//////////////////////////////////////////////////////////


#ifndef ND__NRooTrackerVtx_h
#define ND__NRooTrackerVtx_h
namespace ND {
class NRooTrackerVtx;
} // end of namespace.

#include "ND__JNuBeamFlux.h"
#include "TObjString.h"

namespace ND {
class NRooTrackerVtx : public ND::JNuBeamFlux {

public:
// Nested classes declaration.

public:
// Data Members.
   TObjString* EvtCode;     //generator-specific string with 'event code'
   int         EvtNum;      //event num.
   double      EvtXSec;     //cross section for selected event (1E-38 cm2)
   double      EvtDXSec;    //cross section for selected event kinematics (1E-38 cm2 /{K^n})
   double      EvtWght;     //weight for that event
   double      EvtProb;     //probability for that event (given cross section, path lengths, etc)
   double      EvtVtx[4];    //event vertex position in detector coord syst (SI)
   int         StdHepN;      //number of particles in particle array 
   int         StdHepPdg[100];    //pdg codes (& generator specific codes for pseudoparticles)
   int         StdHepStatus[100];    //generator-specific status code
   double      StdHepX4[100][4];     //4-x (x, y, z, t) of particle in hit nucleus frame (fm)
   double      StdHepP4[100][4];     //4-p (px,py,pz,E) of particle in LAB frame (GeV)
   double      StdHepPolz[100][3];    //polarization vector
   int         StdHepFd[100];         //first daughter
   int         StdHepLd[100];         //last  daughter 
   int         StdHepFm[100];         //first mother
   int         StdHepLm[100];         //last  mother
   int         NEnvc;                 //Number of particles 
   int         NEipvc[100];           //PDG particle code
   float       NEpvc[100][3];         //3-momentum (MeV/c)
   int         NEiorgvc[100];         //Index of parent (Fortran convention: starting at 1)
   int         NEiflgvc[100];         //Flag of final state:   
   int         NEicrnvc[100];         //Escaped nucleus (1) or not (0)
   float       NEcrsx;                //
   float       NEcrsy;                //
   float       NEcrsz;                //
   float       NEcrsphi;              //
   int         NEnvert;               //Number of vertices (including production and exit points)
   float       NEposvert[100][3];     //Position of vertex within nucleus (fm)
   int         NEiflgvert[100];       //Interaction type 
   int         NEnvcvert;             //Number of intermediate particles (including initial and final)
   float       NEdirvert[300][3];     //Direction of particle
   float       NEabspvert[300];       //Absolute momentum in the lab frame (MeV/c)
   float       NEabstpvert[300];      //Absolute momentum in the nucleon rest frame (MeV/c)
   int         NEipvert[300];         //PDG particle code
   int         NEiverti[300];         //Index of initial vertex (pointing to nvert array above)
   int         NEivertf[300];         //Index of final vertex (pointing to nvert array above)
   TObjString* GeomPath;              //
   TObjString* GeneratorName;         //
   TObjString* OrigFileName;          //
   TObjString* OrigTreeName;          //
   int         OrigEvtNum;            //
   int         OrigTreeEntries;       //
   double      OrigTreePOT;           //
   double      TimeInSpill;           //
   int         TruthVertexID;         //

   NRooTrackerVtx();
   NRooTrackerVtx(const NRooTrackerVtx & );
   virtual ~NRooTrackerVtx();

   ClassDef(NRooTrackerVtx,2); // Generated by MakeProject.
};
} // namespace
#endif
