//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed Nov 21 16:59:09 2012 by ROOT version 5.32/00)
//      from the StreamerInfo in file /storage/epp2/phseaj/exercise/prod5_analysis.root
//////////////////////////////////////////////////////////


#ifndef ND__TSHAHashValue_h
#define ND__TSHAHashValue_h
namespace ND {
class TSHAHashValue;
} // end of namespace.

#include "TNamed.h"

namespace ND {
class TSHAHashValue {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned int fHash[5];    //

   TSHAHashValue();
   TSHAHashValue(const TSHAHashValue & );
   virtual ~TSHAHashValue();

};
} // namespace
#endif
