//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Dec  6 16:29:44 2012 by ROOT version 5.32/00)
//      from the StreamerInfo in file /storage/epp2/phseaj/exercise/prod5_analysis.root
//////////////////////////////////////////////////////////


#ifndef ND__TNRooTrackerVtxModule_h
#define ND__TNRooTrackerVtxModule_h
namespace ND {
class TNRooTrackerVtxModule;
} // end of namespace.

#include "ND__TRooTrackerVtxModuleBase.h"

namespace ND {
class TNRooTrackerVtxModule : public ND::TRooTrackerVtxModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TNRooTrackerVtxModule();
   TNRooTrackerVtxModule(const TNRooTrackerVtxModule & );
   virtual ~TNRooTrackerVtxModule();

   ClassDef(TNRooTrackerVtxModule,2); // Generated by MakeProject.
};
} // namespace
#endif
