//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Dec  6 16:29:44 2012 by ROOT version 5.32/00)
//      from the StreamerInfo in file /storage/epp2/phseaj/exercise/prod5_analysis.root
//////////////////////////////////////////////////////////


#ifndef ND__TGRooTrackerVtxModule_h
#define ND__TGRooTrackerVtxModule_h
namespace ND {
class TGRooTrackerVtxModule;
} // end of namespace.

#include "ND__TRooTrackerVtxModuleBase.h"

namespace ND {
class TGRooTrackerVtxModule : public ND::TRooTrackerVtxModuleBase {

public:
// Nested classes declaration.

public:
// Data Members.

   TGRooTrackerVtxModule();
   TGRooTrackerVtxModule(const TGRooTrackerVtxModule & );
   virtual ~TGRooTrackerVtxModule();

   ClassDef(TGRooTrackerVtxModule,2); // Generated by MakeProject.
};
} // namespace
#endif
