//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Dec  6 16:29:43 2012 by ROOT version 5.32/00)
//      from the StreamerInfo in file /storage/epp2/phseaj/exercise/prod5_analysis.root
//////////////////////////////////////////////////////////


#ifndef ND__RooTrackerVtxBase_h
#define ND__RooTrackerVtxBase_h
namespace ND {
class RooTrackerVtxBase;
} // end of namespace.

#include "TObject.h"

namespace ND {
class RooTrackerVtxBase : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.

   RooTrackerVtxBase();
   RooTrackerVtxBase(const RooTrackerVtxBase & );
   virtual ~RooTrackerVtxBase();

   ClassDef(RooTrackerVtxBase,2); // Generated by MakeProject.
};
} // namespace
#endif
