//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Thu Dec  6 16:29:44 2012 by ROOT version 5.32/00)
//      from the StreamerInfo in file /storage/epp2/phseaj/exercise/prod5_analysis.root
//////////////////////////////////////////////////////////


#ifndef ND__TBeamSummaryDataModule_h
#define ND__TBeamSummaryDataModule_h
namespace ND {
class TBeamSummaryDataModule;
} // end of namespace.

#include "ND__TAnalysisHeaderModuleBase.h"
#include "TObject.h"
#include <TString.h>
#include "ND__TBeamSummaryDataModule.h"

namespace ND {
class TBeamSummaryDataModule : public ND::TAnalysisHeaderModuleBase {

public:
// Nested classes forward declaration.
class TBeamSummaryData;

public:
// Nested classes declaration.
class TBeamSummaryData : public TObject {

public:
// Nested classes forward declaration.
class TOtherData;

public:
// Nested classes declaration.
class TOtherData : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   Int_t       MidasEvent;    //
   Int_t       BeamRunNumber;    //
   Int_t       SpillNumber;      //
   Int_t       MRRunNumber;      //
   Int_t       GPSStatus[2];     //
   Int_t       TriggerTime[3];    //
   Int_t       TriggerTimeNanoSecond[3];    //
   Double_t    ProtonsPerSpill[5];          //
   Double_t    ProtonsPerBunch[5][9];       //
   Double_t    BeamTiming[5];               //
   Double_t    BeamBunchTiming[5][9];       //
   Double_t    BeamFlag[5];                 //
   Double_t    BeamBunchFlag[5][9];         //
   Double_t    HornCurrent[3];              //
   Double_t    HornBusBarCurrent[3][5];     //
   Double_t    BeamPositionOnTarget[2];     //
   Double_t    BeamDirectionOnTarget[2];    //
   Double_t    BeamSizeOnTarget[2];         //
   Double_t    MumonSiTotalQ;               //
   Double_t    MumonSiPeak;                 //
   Double_t    MumonSiX;                    //
   Double_t    MumonSiwX;                   //
   Double_t    MumonSiY;                    //
   Double_t    MumonSiwY;                   //
   Double_t    MumonICTotalQ;               //
   Double_t    MumonICPeak;                 //
   Double_t    MumonICX;                    //
   Double_t    MumonICwX;                   //
   Double_t    MumonICY;                    //
   Double_t    MumonICwY;                   //
   Double_t    OTRLightYield;               //
   Double_t    OTRX;                        //
   Double_t    OTRwX;                       //
   Double_t    OTRY;                        //
   Double_t    OTRwY;                       //
   Double_t    OTRXError;                   //
   Double_t    OTRwXError;                  //
   Double_t    OTRYError;                   //
   Double_t    OTRwYError;                  //
   Int_t       GoodGPSFlag;                 //
   Int_t       TriggerFlag;                 //
   Int_t       SpillFlag;                   //
   Int_t       GoodSpillFlag;               //
   Double_t    TargetEfficiency[3];         //
   Int_t       RunType;                     //
   Int_t       MagSetID;                    //

   TOtherData();
   TOtherData(const TOtherData & );
   virtual ~TOtherData();

   ClassDef(TOtherData,2); // Generated by MakeProject.
};

public:
// Data Members.
   Int_t       BeamRunNumber;    //
   Int_t       SpillNumber;      //
   Int_t       GPS1TriggerTime;    //GPS1
   Int_t       GPS1TriggerTimeNanoSecond;    //GPS1
   Double_t    CT5ProtonsPerSpill;           //CT5
   Double_t    CT5ProtonsPerBunch[8];        //CT5
   Double_t    CT5BeamBunchTiming[8];        //CT5
   Int_t       CT5BeamBunchFlag[8];          //CT5
   Double_t    Horn1CurrentSum;              //
   Double_t    Horn2CurrentSum;              //
   Double_t    Horn3CurrentSum;              //
   Int_t       GoodSpillFlag;                //
   TString     BSDVersion;                   //
   ND::TBeamSummaryDataModule::TBeamSummaryData::TOtherData OtherData;                    //

   TBeamSummaryData();
   TBeamSummaryData(const TBeamSummaryData & );
   virtual ~TBeamSummaryData();

   ClassDef(TBeamSummaryData,2); // Generated by MakeProject.
};

public:
// Data Members.

   TBeamSummaryDataModule();
   TBeamSummaryDataModule(const TBeamSummaryDataModule & );
   virtual ~TBeamSummaryDataModule();

   ClassDef(TBeamSummaryDataModule,2); // Generated by MakeProject.
};
} // namespace
#endif
