# Event Codes
#
# This module contains classes useful for reading the event codes generated by GENIE.
#
# Modified 2013.01.26 22:00
#

class Deconstructor: # This class reads through an event code character sequence, and separates it out into the various properties, so that they can be accessed programmaticaly.
	
	def __init__(This):
		
		This.EventCode = "" # The full event code character sequence, which is retained in case it is not properly deconstructed.
		This.Elements = {} # A dictionary of the invidiual properties and their values, populated by Event Code Elements.
		
	def ReadCode(This, Code):
		
		This.EventCode = str(Code)
		This.Elements = {}
				
		TextElements = This.EventCode.split(";") # The event code properties seem to be consistently separated by a semi-colon, therefore this is the first splitting.
		
		for i in TextElements:
			
			Text1 = i.split(":") # The property and its value seem to be consistently separated by a colon, therefore for each property sequence, we split it at the colon.
			
			Element1 = Element()
			if (len(Text1) == 2): # In the event that there was more than one colon, something has gone wrong, so ignore this property.
				if (Text1[0] != "") and (Text1[1] != ""): # If either the property name or value was missing, don't record this property.
					Element1.Reference = This.GetCorrectReference(Text1[0])
					Element1.Content = This.GetCorrectContent(Text1[1])
					This.Elements[Element1.Reference] = Element1
					
					if (Text1[0] == "proc"): # If there is a process property, then add in another element to provide a shorthand code for the process.
						
						Element2 = Element()
						Element2.Reference = "Interaction Code"
						
						Element3 = Element()
						Element3.Reference = "Current Code"
						
						Element4 = Element()
						Element4.Reference = "Process Code"
						
						if (Text1[1] == "Weak[CC],QES"):
							Element2.Content = "W-CC-QS"
							Element3.Content = "CC"
							Element4.Content = "QS"
						elif (Text1[1] == "Weak[CC],RES"):
							Element2.Content = "W-CC-RP"
							Element3.Content = "CC"
							Element4.Content = "RP"
						elif (Text1[1] == "Weak[CC],DIS"):
							Element2.Content = "W-CC-DIS"
							Element3.Content = "CC"
							Element4.Content = "DIS"
						elif (Text1[1] == "Weak[CC],COH"):
							Element2.Content = "W-CC-C"
							Element3.Content = "CC"
							Element4.Content = "C"
						elif (Text1[1] == "Weak[NC],QES"):
							Element2.Content = "W-NC-ES"
							Element3.Content = "NC"
							Element4.Content = "ES"
						elif (Text1[1] == "Weak[NC],RES"):
							Element2.Content = "W-NC-RP"
							Element3.Content = "NC"
							Element4.Content = "RP"
						elif (Text1[1] == "Weak[NC],DIS"):
							Element2.Content = "W-NC-DIS"
							Element3.Content = "NC"
							Element4.Content = "DIS"
						elif (Text1[1] == "Weak[NC],COH"):
							Element2.Content = "W-NC-C"
							Element3.Content = "NC"
							Element4.Content = "C"
							
						This.Elements[Element2.Reference] = Element2
						This.Elements[Element3.Reference] = Element3	
						This.Elements[Element4.Reference] = Element4	
			
	def WriteCode(This):
		
		Text = ""
		
		for Element1 in This.Elements: # Go through each of the elements and write it clearly.
			Text += Element1.WriteClearly()
		
		return Text
		
	def WriteProcessCode(This):
		
		Text = ""
		
		for Element1 in This.Elements:
			if (Element1.Reference == "Process Code"): # Get just the process code.
				Text += Element1.WriteClearly()
		
		return Text
		
	def GetCorrectReference(This, IncorrectReference): # Correct the property references to make them more readable.
		
		CorrectReference = ""
		
		if IncorrectReference == "nu":
			CorrectReference = "Neutrino"
		elif IncorrectReference == "tgt":
			CorrectReference = "Nucleus"
		elif IncorrectReference == "N":
			CorrectReference = "Nucleon"
		elif IncorrectReference == "proc":
			CorrectReference = "Process"
		else:
			CorrectReference = IncorrectReference # In the event that a particular property reference is not recognised, don't change it.
		
		return CorrectReference
		
	def GetCorrectContent(This, IncorrectContent): # Correct the property contents to make them more readable.
		
		CorrectContent = ""
		
		if IncorrectContent == "Weak[CC],QES":
			CorrectContent = "Weak Interaction, Charged-Current (CC) Quasielastic Scattering (QS)"
		elif IncorrectContent == "Weak[CC],RES":
			CorrectContent = "Weak Interaction, Charged-Current (CC) Resonance Production (RP)"
		elif IncorrectContent == "Weak[CC],DIS":
			CorrectContent = "Weak Interaction, Charged-Current (CC) Deep Inelastic Scattering (DIS)"
		elif IncorrectContent == "Weak[NC],QES":
			CorrectContent = "Weak Interaction, Neutral-Current (NC) Elastic Scattering (ES)"
		elif IncorrectContent == "Weak[NC],RES":
			CorrectContent = "Weak Interaction, Neutral-Current (NC) Resonance Production (RP)"
		elif IncorrectContent == "Weak[NC],DIS":
			CorrectContent = "Weak Interaction, Neutral-Current (NC) Deep Inelastic Scattering (DIS)"
		else:
			CorrectContent = IncorrectContent # In the event that a particular property content is not recognised, don't change it.
		
		return CorrectContent
		

class Element: # This is a container class for sections of an event code, used by the Event Code Deconstructor.
	
	def __init__(This, Reference = "", Content = ""):
		This.Reference = Reference
		This.Content = Content
		
	def Write(This): # Write in the normal way.
		Text = This.Reference + ":" + This.Content + ";"
		return Text
		
	def WriteClearly(This): # Write in a way which is easily readable.
		Text = This.Reference + ": " + This.Content + ". "
		return Text
		
	
